# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency

remote_theme: raviriley/agency-jekyll-theme

url    : "teamrakijada" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ADA_Data_Story" # the subpath of your site, e.g. /blog

title      : Do we rate as we write?
description: "Are there patterns in the way we write reviews despite the grade we give?
	    		What do people write about the most and when?"
author     : Team rakijada
logo       : True

locale: "en-US"

collections:
  portfolio:

markdown: kramdown